### ISSUE TITLE
large error

### ISSUE THREAD

**Issue by panglei-math-zju** [brandstetter-johannes/LPSDA#3]
Wonderful job!
I'm having some problems running the code，
KdV, end_time=40, nt=200, nt_effective=200, nx=256, L=128, samples=512, batch_size=64.
After 10 epochs, the vlidation error is larger than 1, and the train speed(4070Ti) is slow(maybe it's caused by change num_workers from 4 to 0).
Looking forward to your reply.

**Comment by panglei-math-zju** [comment]
and the utilization rate of gpu is less than ten percent

**Comment by brandstetter-johannes** [comment]
Hi @panglei-math-zju, thanks a lot! Hmmm I couldn't reproduce this error, using a V100 for training. could you try with num_workers=4?
